---
title: "BIOL 432 - Assignment 1"
author: "David Griffin"
date: '2023-01-11'
output: html_document
---
[Link to my repository](https://github.com/davidgriffin124/BIOL432_Assignment1)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading Library
```{r}
library(dplyr)
library(ggplot2)
```

# Script generating limb data for 5 species of capuchin monkey
```{r}
source('dataGenerato.R')
```

# Script estimating limb volume and adding column
```{r}
source('volumeEstimato.R')
```

# Loading revised limb data
```{r}
limbdat = read.csv("measurements.csv")
```

# Sorting data by Species, then b Observer, then by Limb Volume
```{r}
limbdat = limbdat %>%
  arrange(Organism, Observer, Limb_volume)
```


# Table displaying average Limb Volume by Species
```{r}
limbdat %>%
  group_by(Organism)%>%
  summarize(Average_Limb_Volume = mean(Limb_volume))
```


# Table displaying number of observations by Species x Observer
```{r}
limbdat %>%
  group_by(Organism, Observer) %>%
  count()
```

# Box plot comparing species
```{r}

boxplot1 <- ggplot(limbdat, aes(x=Organism, y=Limb_volume)) + 
  geom_boxplot() + theme_bw()

boxplot1
```

```{r}
ggplot (data = limbdat, aes(x = Limb_volume)) + geom_histogram() + xlab("Limb Volume") + ylab("Count") + facet_wrap(~Organism, nrow=3, ncol=2) + theme_bw()

  
  
  scale_colour_gradient(limits=c(-1, 1), low = "green", high = "red") + scale_y_continuous(limits=c(1, 1000), breaks=c(1, 10, 100, 1000), trans="log1p") + xlab("Nucleotide Position") + ylab("Read Count Per Million") 
```

